title: Faruk Arslan
email: sh4d0wless@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  sh4d0wless'ın çılgın blog sayfası
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sh4d0wlesss.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sh4d0wlesss
github_username:  sh4d0wlesss

# Build settings
markdown: kramdown
#theme: minima
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed


header_pages:
  - index.md
  - about.md


style: dark

footer: '<a target="_blank" href="https://www.hackthebox.eu/home/users/profile/175360">Hack The Box</a> |<a target="_blank" href="https://ctftime.org/user/66807">CTFtime</a> |<a target="_blank" href="https://github.com/sh4d0wlesss/">github</a> | <a target="_blank" href="https://twitter.com/sh4d0wlesss">twitter</a> | <a target="_blank" href="https://www.linkedin.com/in/faruk-arslan/">linkedin</a> '

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
